# Introduction to Numpy

In this Jupyter notebook the courses cover a useful introduction about Numpy library

In [2]:
# load the library
import numpy as np

### Creating arrays

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [9]:
a = np.array([1, 3, 5, 7, 9])

In [11]:
# to access a specific element in the array
a[2]

5